---
- name: Check if it is already installed
  command: dpkg-query -W google-chrome-stable
  register: chrome_check_deb
  failed_when: chrome_check_deb.rc > 1
  changed_when: chrome_check_deb.rc == 1

- name: Does the apt file exist?
  stat:
    path: "{{ chrome_apt_file }}"
  register: google_apt_file
  ignore_errors: true
  changed_when: false
  when: chrome_check_deb.rc == 1

- name: Add the signing key to apt-key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  when: chrome_check_deb.rc == 1 and not google_apt_file.stat.exists

- name: Add repo if required
  become: true
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    update_cache: true
    filename: "{{ google_chrome_list_file }}"
  when: chrome_check_deb.rc == 1 and not google_apt_file.stat.exists

- name: Update apt cache
  become: true
  apt:
    update_cache: true
  when: chrome_check_deb.rc == 1 and not google_apt_file.stat.exists

- name: Install package
  become: true
  apt:
    pkg: google-chrome-stable
    state: present
  when: chrome_check_deb.rc == 1
