---
- name: Check if it is already installed
  command: dpkg-query -W smplayer
  register: smplayer_check_deb
  failed_when: smplayer_check_deb.rc > 1
  changed_when: smplayer_check_deb.rc == 1

- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present
  when: smplayer_check_deb.rc == 1

- name: Add Repository source
  become: true
  apt_repository:
    repo: 'ppa:rvm/smplayer'
    state: present
    update_cache: true

- name: Install packages
  become: true
  apt:
    state: latest
    pkg: "smplayer, smplayer-themes, smplayer-skins"
