- name: "Ubuntu family local setup"
  hosts: 127.0.0.1
  connection: local
  vars:
    - ubuntu_release_name: focal
    - vault_download: https://releases.hashicorp.com/vault/1.2.3/vault_1.2.3_linux_amd64.zip
    - vault_file: "{{ vault_download | basename }}"

  roles:
    - common
    - fonts
    - code
    - docker
    - git
    - github-cli
    - google-chrome
    - hub
    - keepassxc
    - ngrok
    - smplayer
    - peek

  tasks:
  - name: Remove useless packages from the cache
    become: True
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    become: True
    apt:
      autoremove: yes

    # - name: download vault
    #   get_url:
    #     url: "{{ vault_download }}"
    #     dest: /tmp
    # - name: unzip vault download
    #   become: True
    #   unarchive:
    #     src: /tmp/{{ vault_file }}
    #     dest: /usr/local/bin
    #     remote_src: True
    # - name: set permissions and ownersip correct for vault executable
    #   become: True
    #   file:
    #     path: /usr/local/bin/vault
    #     owner: vault
    #     group: vault
    #     mode: 0755
    # - name: set memlock capability on vault executable for security
    #   become: True
    #   shell: >
    #     setcap cap_ipc_lock=+ep /usr/local/bin/vault
    # - name: create vault systemd service to run vault as system daemon
    #     become: true
    #     shell: |
    #       echo "[Unit]
    #       Description="a tool for managing secrets"
    #       Documentation=https://www.vaultproject.io/docs/
    #       Requires=network-online.target
    #       After=network-online.target
    #       ConditionFileNotEmpty=/etc/vault.d/vault.hcl

    #       [Service]
    #       User=vault
    #       Group=vault
    #       ProtectSystem=full
    #       ProtectHome=read-only
    #       PrivateTmp=yes
    #       PrivateDevices=yes
    #       SecureBits=keep-caps
    #       AmbientCapabilities=CAP_IPC_LOCK
    #       Capabilities=CAP_IPC_LOCK+ep
    #       CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
    #       NoNewPrivileges=yes
    #       ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
    #       ExecReload=/bin/kill --signal HUP $MAINPID
    #       KillMode=process
    #       KillSignal=SIGINT
    #       Restart=on-failure
    #       RestartSec=5
    #       TimeoutStopSec=30
    #       StartLimitIntervalSec=60
    #       StartLimitBurst=3
    #       LimitNOFILE=65536

    #       [Install]
    #       WantedBy=multi-user.target" > /etc/systemd/system/vault.service
    #     args:
    #       creates: /etc/systemd/system/vault.service
