---
- name: Run "apt-get update"
  become: true
  apt:
    update_cache: true
    cache_valid_time: "3600"
  ignore_errors: true

- name: Install packages
  become: true
  apt:
    state: latest
    pkg: "stow, neovim, htop, conky-all, byobu, evolution-ews, guake, autokey-gtk, slack-desktop, powerline, curl, unzip, bat, python3-venv"

- name: Check batcat is present before moving cat
  stat:
    path: "{{ batcat_path }}"
  register: bat_cat
  ignore_errors: true

- name: Also check if we already have bat set as default
  shell: |
    cat --version | awk '{print $1}'
  register: current_cat

- name: Copy cat to oldcat
  become: true
  copy:
    src: "{{ cat_path }}"
    dest: "{{ oldcat_path }}"
  when: bat_cat.stat.exists and current_cat.stdout != bat

- name: Remove cat
  become: true
  file:
    path: "{{ cat_path }}"
    state: absent
  when: bat_cat.stat.exists and current_cat.stdout != bat

- name: Set Batman to be a default cat be setting alternative of cat
  become: true
  alternatives:
    name: cat
    link: "{{ cat_path }}"
    path: "{{ batcat_path }}"
    priority: 20
  when: bat_cat.stat.exists and current_cat.stdout != bat

- name: Set {{ oldcat_path }} to be a backup cat
  become: true
  alternatives:
    name: cat
    link: "{{ cat_path }}"
    path: "{{ oldcat_path }}"
    priority: 10
  when: bat_cat.stat.exists and current_cat.stdout != bat
