---
- name: Check if it is already installed
  command: dpkg-query -W peek
  register: peek_check_deb
  failed_when: peek_check_deb.rc > 1
  changed_when: peek_check_deb.rc == 1

- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present
  when: peek_check_deb.rc == 1

- name: Add Repository source
  become: true
  apt_repository:
    repo: 'ppa:peek-developers/stable'
    state: present
    update_cache: true

- name: Install packages
  become: true
  apt:
    state: latest
    pkg: peek
