---
#- name: "Check if git is already installed?"
#  stat:
#    path: /usr/bin/git
#  register: git_status

- name: Install apt-transport-https
  become: True
  apt:
    name: apt-transport-https
    state: present
  #when: not git_status.stat.exists

- name: Add Git repository source
  become: True
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
    update_cache: True
    #  when: not git_status.stat.exists

- name: Install Git and related packages
  become: True
  apt:
    state: latest
    pkg:
      - git
      - git-flow
      - hub
      - git-lfs
