---
- name: Check if it is already installed
  command: dpkg-query -W git
  register: git_check_deb
  failed_when: git_check_deb.rc > 1
  changed_when: git_check_deb.rc == 1

- name: Install apt-transport-https
  become: True
  apt:
    name: apt-transport-https
    state: present
  when: git_check_deb.rc == 1

- name: Add repository source
  become: True
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
    update_cache: True

- name: Install packages
  become: True
  apt:
    state: latest
    pkg: "git, git-flow, hub, git-lfs"
