---
- name: Check if it is already installed
  command: dpkg-query -W code
  register: code_check_deb
  failed_when: code_check_deb.rc > 1
  changed_when: code_check_deb.rc == 1

- name: Get the repository key location info
  stat:
    path: "{{ vscode_gpg_location }}/{{ vscdoe_gpg_filename }}"
  register: vscode_gpg_location_info
  ignore_errors: true
  when: code_check_deb.rc == 1

- name: Create a directory if it does not exist
  file:
    path: "{{ code_dir_tmp }}"
    state: directory
    mode: '0755'
  when: code_check_deb.rc == 1 and not vscode_gpg_location_info.stat.exists

- name: Download the apt repository key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ code_dir_tmp }}/{{ asc_file_tmp }}"
  when: code_check_deb.rc == 1 and not vscode_gpg_location_info.stat.exists

- name: Convert The Key using gpg --armor
  shell: |
    set -o pipefail
    "cat {{ code_dir_tmp }}/{{ asc_file_tmp }} | gpg --dearmor > {{ code_dir_tmp }}/{{ vscdoe_gpg_filename }}"
  args:
    executable: /bin/bash
  when: code_check_deb.rc == 1 and not vscode_gpg_location_info.stat.exists

- name: Copy file with owner and permissions
  become: true
  copy:
    src: "{{ code_dir_tmp }}/{{ vscdoe_gpg_filename }}"
    dest: "{{ vscode_gpg_location }}/{{ vscdoe_gpg_filename }}"
    owner: root
    group: root
    mode: '0644'
  when: code_check_deb.rc == 1 and not vscode_gpg_location_info.stat.exists

- name: Remove the directory and files in it created before
  file:
    path: "{{ code_dir_tmp }}"
    state: absent
  ignore_errors: true
  when: code_check_deb.rc == 1

- name: Create the list file
  become: true
  file:
    path: "{{ vscode_list_file }}"
    state: touch
  ignore_errors: true
  changed_when: false
  when: code_check_deb.rc == 1

- name: Add the repository
  become: true
  lineinfile:
    path: "{{ vscode_list_file }}"
    line: "deb [arch=amd64 signed-by={{ vscode_gpg_location }}/{{ vscdoe_gpg_filename }}] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    regexp: '^deb.*main$'
  when: code_check_deb.rc == 1

- name: Install apt transport https
  become: true
  apt:
    state: latest
    pkg: apt-transport-https
  when: code_check_deb.rc == 1

- name: Run "apt-get update"
  become: true
  ignore_errors: true
  apt:
    update_cache: true
  when: code_check_deb.rc == 1

- name: Install package
  become: true
  apt:
    state: latest
    pkg: code
