---
- name: Remove conflicting packages
  become: True
  apt:
    name: docker docker-engine docker.io containerd runc
    state: absent

- name: Check if it is already installed
  command: dpkg-query -W docker-ce
  register: docker_check_deb
  failed_when: docker_check_deb.rc > 1
  changed_when: docker_check_deb.rc == 1

- name: "Check if binary is already present"
  stat:
    path: /usr/bin/docker
  register: docker

- name: Install apt-transport-https
  become: True
  apt:
    name: apt-transport-https
    state: present
  when: docker_check_deb.rc == 1 and not docker.stat.exists

- name: Add the repository key
  become: True
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_check_deb.rc == 1 and not docker.stat.exists

- name: Add the repository source
  become: True
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release_name }} stable"
    state: present
    update_cache: True
    filename: docker
  when: docker_check_deb.rc == 1 and not docker.stat.exists

- name: Update apt cache
  become: True
  apt:
    update_cache: True
    cache_valid_time: "3600"
  ignore_errors: True
  when: docker_check_deb.rc == 1

- name: Install packages
  become: True
  apt:
    pkg: docker-ce
    state: present
  when: docker_check_deb.rc == 1

- name: "Add the user {{ user_to_add_to_docker_group }} to correct group"
  become: True
  user:
    name: "{{ user_to_add_to_docker_group }}"
    append: True
    groups:
      - docker

- name: Reload service configuration
  become: True
  service:
    name: docker
    state: started
  changed_when: docker_check_deb.rc == 1
