---
- name: Add the ppa
  become: true
  apt_repository:
    repo: 'ppa:phoerious/keepassxc'
    state: present
    update_cache: true

- name: Install the package
  become: true
  apt:
    state: latest
    pkg: keepassxc
