---
- name: Check if it is already installed
  command: dpkg-query -W keepassxc
  register: keepassxc_check_deb
  failed_when: keepassxc_check_deb.rc > 1
  changed_when: keepassxc_check_deb.rc == 1

- name: Add the ppa
  become: yes
  apt_repository:
    repo: 'ppa:phoerious/keepassxc'
    state: present
    update_cache: yes
  when: keepassxc_check_deb.rc == 1

- name: Install the package
  become: yes
  apt:
    state: latest
    pkg: keepassxc
  when: keepassxc_check_deb.rc == 1
