# This is a basic workflow to help you get started with Actions

name: AnsibleLint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -U pip && pip install -r requirements.txt
    - name: Run Yaml Lint
      run: yamllint .
    - name: Run Ansible Lit
      run: ansible-lint local-setup/post_install.yml
    - name: Run Ansible Playbook Syntax Check
      run: ansible-playbook --syntax-check local-setup/post_install.yml
